# Generated by Django 3.2.8 on 2021-11-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
